[package]
name = "badapple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.ffmpeg-next]
version = "4.3.0"
default-features = false
features = ["codec", "format", "software-scaling"]